### ISSUE TITLE
Error: Cannot load kernel without a valid FS

### ISSUE THREAD

**Issue by dmenezesgabriel** [jupyterlite/xeus#256]
## Description

After updating `jupyterlite-xeus` to version `4.0.3` and my JavaScript, SQLite and Python kernels, I cannot use neither `xeus-javascript` or `xeus-sqlite`, but `xeus-python` is working fine.

## Reproduce

My jupyterlite is hosted on GitHub pages. Below are my environment specs:

build-environment.yml:

```yml
name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server=2.16.0
  - jupyterlite-core=0.6.2
  - jupyterlite-xeus=4.0.3
  - jupyterlite-javascript-kernel=0.3.0
  - jupyterlite-pyodide-kernel=0.6.1
  - jupyterlite-terminal=0.2.1
```

environment.yml
```yml
name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - xeus-sqlite
  - xeus-javascript=0.4.0
  - scikit-learn=1.1.3
  - scipy=1.11.1
  - pandas=2.2.3
  - numpy=1.25.2
  - matplotlib=3.9.4
  - plotly=6.1.2
  - ipywidgets=8.1.7
  - rich=14.0.0
  - jupytext=1.17.2
  - jupyterlab-language-pack-pt-BR
  # - jupyterlab-open-url-parameter
  # - jupyterlab-filesystem-access
  - pip
  - pip:
      - jupyterlite-ai==0.7.0
```

Once I deployed and click on the launcher for `Javascript (xjavascript)` or `xsqlite` the kernels take some time then I got an error message:

![Image](https://github.com/user-attachments/assets/0a584d89-fb0f-46ce-9d5c-d193c68f34e3)

![Image](https://github.com/user-attachments/assets/cb764756-5de1-464a-9507-f60eccc5e257)

![Image](https://github.com/user-attachments/assets/e522310b-8ed7-4eca-80ac-052ddcc1f215)

I also have tried downgrade just the kernels versions (not `jupyterlite-xeus`) for the previous ones and got the same errors.

## Expected behavior

I would expect that the kernel load without errors as it was working on `jupyterlite-xeus=3.0.0` for me.

## Context

- JupyterLite version: `jupyterlite-core=0.6.2`
- Operating System and version: `Debian`
- Browser and version: Chrome Version 137.0.7151.86 (Official Build) (64-bit)
