### ISSUE TITLE
Can't start kernel on 4.0.5

### ISSUE THREAD

**Issue by trungleduc** [jupyterlite/xeus#260]
## Description
I can't start the kernel and get 404 on this request `http://127.0.0.1:5445/xeus/xeus-kernels/libxeus.so`

![Image](https://github.com/user-attachments/assets/9d4e66b0-6147-4269-8772-9b9424631fd8)

## Reproduce

1. Create new env

```bash
mamba create -n xeus-bug python=3.13 jupyterlite jupyterlite-xeus
```
2. Create `environment.yml` file
```yaml
name: xeus-kernels
channels:
  - https://prefix.dev/emscripten-forge-dev
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-python
```

3. Build  and serve JupyterLite
```
jupyter lite build  --output-dir _output
python -m http.server 5445 --directory _output
```

4. Go to `http://127.0.0.1:5444/` and start a kernel

## Expected behavior

I can start a kernel

## Context

```
jupyterlite               0.6.2              pyhe01879c_0    conda-forge
jupyterlite-core          0.6.2              pyhe01879c_0    conda-forge
jupyterlite-xeus          4.0.5              pyhd8ed1ab_0    conda-forge
```
