### ISSUE TITLE
%load doesn't work as hoped on https

### ISSUE THREAD

**Issue by stonebig** [jupyterlite/xeus#68]
Trying to get this to work

````
%load  https://raw.githubusercontent.com/MicrosoftDocs/mslearn-introduction-to-machine-learning/main/graphing.py 
````

I get an error:
````
/tmp/xeus-python-kernel/envs/xeus-python-kernel/lib/python3.10/urllib/request.py in unknown_open(self, req)
   1417     def unknown_open(self, req):
   1418         type = req.type
-> 1419         raise URLError('unknown url type: %s' % type)
   1420 
   1421 def parse_keqv_list(l):

URLError: <urlopen error unknown url type: https>
````

is it a limitation ? is there a simple workaround ? (via javascript alternative ?)

**Comment by martinRenou** [comment]
Using the latest `jupyterlite-xeus` version, you can now install the `requests` package and use it:

```yml
name: xeus-kernels
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - requests
```
