### ISSUE TITLE
Add scripts to build the documentation

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/xeus#79]
### Problem

Currently there is no easy way to build the documentation locally.

### Suggested Improvement

- Add scripts to build the documentation. For example similar to:

https://github.com/voila-dashboards/voila/blob/5aa861dc153215c66d8ccdff040f4ac868d7af3a/pyproject.toml#L145-L151

```toml
[tool.hatch.envs.docs]
features = ["docs"]

[tool.hatch.envs.docs.scripts]
build = "sphinx-build -W -b html docs docs/build/html"
watch = "sphinx-autobuild -W -b html docs docs/build/html --host 0.0.0.0"
serve = "python -m http.server --directory docs/build/html"
```

- Add a section to the contributing guide about contributing to the documentation
